### ISSUE TITLE
Feature Request: Support get buffers method like `cmp-buffer`

### ISSUE THREAD

**Issue by captainko** [tzachar/cmp-fuzzy-buffer#2]
It's a nice plugin you got here :smile: 
Original: https://github.com/hrsh7th/cmp-buffer#get_bufnrs-type-fun-number
# Examples: 
get_bufnrs (type: fun(): number[])
Default: `function() return { vim.api.nvim_get_current_buf() } end`

A function that specifies the buffer numbers to complete.

You can use the following pre-defined recipes.

## All buffers
```lua
get_bufnrs = function()
  return vim.api.nvim_list_bufs()
end
```
## Visible buffers
```lua
get_bufnrs = function()
  local bufs = {}
  for _, win in ipairs(vim.api.nvim_list_wins()) do
    bufs[vim.api.nvim_win_get_buf(win)] = true
  end
  return vim.tbl_keys(bufs)
end
```

**Comment by tzachar** [comment]
Interesting.

The only thing I am afraid is performance issues, but this is up to the user...
