### ISSUE TITLE
Does not treat `/` as a word separators 

### ISSUE THREAD

**Issue by pBorak** [tzachar/cmp-fuzzy-buffer#3]
I am not sure whether is a bug or not but when there are words that contain '/' I'd expect that I am able to fuzzy search/complete part of the word up to the slash, currently it's impossible like in the screenshots below.
There's only one option to select 'tpope/vim' not 'tpope' phrase itself. 

<img width="450" alt="Screenshot 2021-11-03 at 22 17 14" src="https://user-images.githubusercontent.com/45797239/140194097-2817470e-adef-49f6-a43c-39e1f3e55302.png">

For what is worth I am using FZF version.

**Comment by tzachar** [comment]
This should be fixed in a407afffc83e0d7bf48a3de81387592a6233f6ee
