### ISSUE TITLE
Support for magic search

### ISSUE THREAD

**Issue by JoseConseco** [tzachar/cmp-fuzzy-buffer#4]
```lua
cmp.setup.cmdline('/', {
  sources = {
		-- { name = 'rg'}, -- or 'buffer'
		{name = 'fuzzy_buffer'}
  }
})
```
magic search in vim simplifies regex but it confuses cmp-fuzzy-buffers, eg when I search for import word:
`/\vimp`
the cmp-fzzy will not show suggestions related to  'imp'
`/imp`  works ok though. 
I made mapping that automatically  maps `/` to `/\v` and this breaks the cmp-fuzzy. I hope there is way to filter out the [magic](https://vim.fandom.com/wiki/Simplifying_regular_expressions_using_magic_and_no-magic) characters.
I guess similar issue is affecting other cmdLine plugins. Maybe I should report it on : https://github.com/hrsh7th/cmp-cmdline  ?
Done: https://github.com/hrsh7th/cmp-cmdline/issues/14

**Comment by tzachar** [comment]
IDK. Maybe just stripping the `\v` from the pattern?
But what would happen when users add other control characters?

**Comment by JoseConseco** [comment]
I see there is option to define keyword_pattern but when I try to config: 
```lua
		use {'tzachar/cmp-fuzzy-buffer', requires = {'hrsh7th/nvim-cmp', 'tzachar/fuzzy.nvim'},
			config = function()
				require('cmp-fuzzy-buffer').setup({
					 keyword_pattern = '[=[[^[:blank:]].*]=]'
				})
			end
		}  
```
I get error: 
![image](https://user-images.githubusercontent.com/13521338/141291484-51c196e7-ef09-42f1-9b60-58926fa12de3.png)
I also tried `require'fuzzy-buffer'` but it wont work either. I wanted to try removing all magic sequences - something like
$(^(\v|\m|\V|\M))  - not sure if this is correct syntax.  Also I'm not sure how to setup keyword_pattern only for command line.

**Comment by tzachar** [comment]
There is no `setup` function.
You need to pass your keyword pattern in the `opts` field when registering the source.
Something like this:

```lua
require'cmp'.setup {
  sources = cmp.config.sources({
    { 
       name = 'fuzzy_buffer' ,
       opts = {    keyord_pattern = 'YOUR_PATTERN,  },
    },
  })
}

```

You can then pass different patterns in cmdline mode, when setting the source in cmdline.

**Comment by JoseConseco** [comment]
I think its not possible to filter the \v \m etc. with keyword_patters after all. There are problems with vim.regex, and proper handling of  conversion `\`  from lua to vim regex. I'm even sure if keyword_pattern is responsible for parsing user cmd line input?

**Comment by tzachar** [comment]
The following will probably work for you. However, I will not apply it in general...
```diff
diff --git a/lua/cmp_fuzzy_buffer/init.lua b/lua/cmp_fuzzy_buffer/init.lua
index ed3355c..fb2e89d 100644
--- a/lua/cmp_fuzzy_buffer/init.lua
+++ b/lua/cmp_fuzzy_buffer/init.lua
@@ -86,7 +86,7 @@ source.complete = function(self, params, callback)
                end
                local items = {}
                local set = {}
-           local matches = matcher:filter(pattern, lines)
+         local matches = matcher:filter(pattern:gsub([[\v]], ''), lines)
                for _, result in ipairs(matches) do
                        local line, positions, score = unpack(result)
                        local min, max = minmax(positions)
```

**Comment by aMOPel** [comment]
Somewhat related to this topic:

It took me a while to figure out, why a search sometimes wouldn't take me to the search match. It was because I had `set magic`. 

`'magic'` on is the default and 
> WARNING: Switching this option off most likely breaks plugins!

You can switch off magic with `/\M` but that poses the same problem as using `/\v`.

I'd propose that you either
* add some check in the plugin that turns it off (temporarily) when using search or
* escape magic chars in completion if `set magic`. 
That at least includes `.$*~[]\`

Thanks for your work :)
